version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  jaeger:
    image: jaegertracing/all-in-one:1.42
    container_name: jaeger
    ports:
      - "5775:5775/udp"       # For receiving traces (UDP)
      - "6831:6831/udp"       # For receiving traces (UDP)
      - "6832:6832/udp"       # For receiving traces (UDP)
      - "5778:5778"           # For agent's HTTP admin port
      - "16686:16686"         # For Jaeger UI
      - "14268:14268"         # For collector HTTP endpoint
      - "14250:14250"         # For gRPC
      - "9411:9411"           # For Zipkin
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
